### ISSUE TITLE
Non-functioning account APIs

### ISSUE THREAD

**Issue by alapidas** [zricethezav/go-tdameritrade#16]
It looks like all of these functions are not 100% implemented, is there a reason for that other than time/bandwidth?  The response body gets read, which makes it unreadable by the caller, so the functions are affectively useless.

https://github.com/zricethezav/go-tdameritrade/blob/master/tdameritrade/accounts.go#L416-L487

**Comment by zricethezav** [comment]
@alapidas I haven't been maintaining this for a while. I'll take a look at finishing it when I get some time. I'll happily accept PRs if they come in

**Comment by lyonplus** [comment]
I have a patch for it, I will create a pull request after my merge request https://github.com/zricethezav/go-tdameritrade/pull/25 is merged.

**Comment by zricethezav** [comment]
Thanks for fixing it @lyonplus, released with 0.2.1

**Comment by lyonplus** [comment]
> Thanks for fixing it @lyonplus, released with 0.2.1

Thanks for accepting my pull request. It makes my reference easier. And hopefully it will help someone else.
