### ISSUE TITLE
replace anonymous struct for Candles

### ISSUE THREAD

**Issue by phamdt** [zricethezav/go-tdameritrade#27]
I'm integrating your library into my application and discovered that I can't access an individual candle from the PriceHistory API. I can only access the list of `Candles` which references an anonymous struct. In my code it would be convenient if I could pass around the individual candle. I can make the PR if this is acceptable to you.

**Comment by zricethezav** [comment]
@phamdt
> I can make the PR if this is acceptable to you.

Go for it 😄
